### ISSUE TITLE
Searching seems to be case sensitive

### ISSUE THREAD

**Issue by mudrd8mz** [jpahullo/moodle-repository_searchable#1]

**Comment by jpahullo** [comment]
As other cases, I tried it worked for main cases. Case sensitive or not is a feature I wanted to treat after it works.

I thought about it as an additional checkbox in the search form, to allow user to filter properly. Do you like it?

**Comment by mudrd8mz** [comment]
If it was me, I would simply make the search case insensitive all the time, no need for a setting. I can't think of a valid use why someone would need case sensitive search.

**Comment by jpahullo** [comment]
Ok. I thought it only for advanced users. But, it is simpler to maintain and practical as you suggest. Thanks!
