### ISSUE TITLE
Pollutes $SESSION root namespace

### ISSUE THREAD

**Issue by mudrd8mz** [jpahullo/moodle-repository_searchable#3]
All those `$SESSION->searchable_ ...` and friends should really live under a common namespace, not in the root of the session object. E.g. `$SESSION->repository_searchable->searchable_ ...`

Also, those PARAM_RAW used directly for naming the properties names look malicious.

**Comment by jpahullo** [comment]
Yes, you're right. I tried to make it work first. Then, I'd have add security fixes.

**Comment by jpahullo** [comment]
This issue is solved with my last commit 0f8c47b . Closing.

Thanks for reporting!
